FROM ubuntu:latest as builder

RUN apt update && apt install -y git maven

WORKDIR /app

RUN git clone https://github.com/shashirajraja/onlinebookstore.git && \
	mvn -f onlinebookstore/pom.xml clean install

RUN git clone https://github.com/OpqTech/tomcat-config.git


FROM tomcat:latest

WORKDIR /usr/local/tomcat

COPY --from=builder /app/tomcat-config/ tomcat-config/

RUN rm -rf webapps && \
	mv webapps.dist webapps && \
	cp ./tomcat-config/context.xml ./webapps/host-manager/META-INF/context.xml && \
	cp ./tomcat-config/context.xml ./webapps/manager/META-INF/context.xml && \
	cp ./tomcat-config/tomcat-users.xml ./conf/tomcat-users.xml && \
	rm -rf ./tomcat-config
	
COPY --from=builder /app/onlinebookstore/target/*.war webapps/

EXPOSE 8080
