FROM tomcat

RUN apt update && apt install -y git maven

WORKDIR /usr/local/tomcat

RUN git clone https://github.com/OpqTech/tomcat-config.git && \
	rm -rf webapps && \
	mv webapps.dist webapps && \
	cp ./tomcat-config/context.xml ./webapps/host-manager/META-INF/context.xml && \
	cp ./tomcat-config/context.xml ./webapps/manager/META-INF/context.xml && \
	cp ./tomcat-config/tomcat-users.xml ./conf/tomcat-users.xml && \
	rm -rf ./tomcat-config
	
RUN git clone https://github.com/shashirajraja/onlinebookstore.git && \
	mvn -f onlinebookstore/pom.xml clean install -DskipTests && \
	cp onlinebookstore/target/*.war webapps/ && \
	rm -rf onlinebookstore/

EXPOSE 8080
